In [1]:
import torch


In [3]:
x=torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [4]:
x.shape


torch.Size([12])

In [6]:
x.numel()


12

In [22]:
q=torch.ones(3,6)
q

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

In [7]:
y=x.reshape(2,6)

In [8]:
y

tensor([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]])

In [11]:
torch.zeros([2,3,4])

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [14]:
torch.tensor([[[1,2,3,4],[5,6,7,8]],[[1,2,3,4],[-1,-2,-3,-4]]])


tensor([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8]],

        [[ 1,  2,  3,  4],
         [-1, -2, -3, -4]]])

In [17]:
torch.tensor([[[1,2,3,4],[5,6,7,8]],[[1,2,3,4],[-1,-2,-3,-4]]]).shape



torch.Size([2, 2, 4])

In [18]:
torch.tensor([[1,2,3,4],[5,6,7,8]]).shape

torch.Size([2, 4])

In [31]:
X=torch.arange(12).reshape(3,4)
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [33]:
Y=torch.tensor([[4,3,2,1],[6,5,4,3],[10,9,8,7]])
Y

tensor([[ 4,  3,  2,  1],
        [ 6,  5,  4,  3],
        [10,  9,  8,  7]])

In [34]:
X==Y

tensor([[False, False,  True, False],
        [False,  True, False, False],
        [False,  True, False, False]])

In [25]:
torch.cat((X,Y),dim=0)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [ 4,  3,  2,  1],
        [ 6,  5,  4,  3],
        [10,  9,  8,  7]])

In [26]:
torch.cat((X,Y),dim=1)

tensor([[ 0,  1,  2,  3,  4,  3,  2,  1],
        [ 4,  5,  6,  7,  6,  5,  4,  3],
        [ 8,  9, 10, 11, 10,  9,  8,  7]])

In [28]:
X==Y

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

In [52]:
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [53]:
Y

tensor([[ 4,  4,  4,  4],
        [10, 10, 10, 10],
        [18, 18, 18, 18]])

In [54]:
Y


tensor([[ 4,  4,  4,  4],
        [10, 10, 10, 10],
        [18, 18, 18, 18]])

In [57]:
before=id(Y)
Y+=X
id(Y)==before

True

In [58]:
id(Y)

140368875944784

In [59]:
id(before)

140368873989360

In [60]:
z=torch.zeros_like(Y)
z

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]])

In [61]:
id(z)

140368875997360

In [62]:
z[ : ]=X+Y


In [63]:
z

tensor([[ 4,  7, 10, 13],
        [22, 25, 28, 31],
        [42, 45, 48, 51]])

In [64]:
id(z)

140368875997360

In [65]:
A=X.numpy()
B=torch.tensor(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

In [66]:
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [67]:
B

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])